FROM openjdk
WORKDIR uas/lib
COPY ./target/userauthenticationservice-0.0.1-SNAPSHOT.jar /uas/lib/userauthenticationservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","userauthenticationservice-0.0.1-SNAPSHOT.jar"]